-- ====================================================================
-- CLINEVO SMART INBOX ASSISTANT — ORACLE ENTERPRISE PL/SQL DDL SCHEMA
-- Target Database: Oracle Database 19c / 21c Enterprise Edition
-- Compliance: 21 CFR Part 11 & GVP Module VI Audit Trail Requirements
-- ====================================================================

-- 1. Sequences for Primary Keys
CREATE SEQUENCE SEQ_INTAKE_MESSAGES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ATTACHMENTS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ICSR_REPORTS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PQC_REPORTS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MEDICAL_INFO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AUDIT_LOG START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_LITERATURE_ARTICLES START WITH 1 INCREMENT BY 1 NOCACHE;

-- 2. Master Table: INTAKE_MESSAGES
CREATE TABLE INTAKE_MESSAGES (
    ID NUMBER(19) DEFAULT SEQ_INTAKE_MESSAGES.NEXTVAL PRIMARY KEY,
    MESSAGE_ID VARCHAR2(255) NOT NULL UNIQUE,
    SENDER VARCHAR2(255),
    SENDER_EMAIL VARCHAR2(255),
    RECIPIENT VARCHAR2(255),
    SUBJECT VARCHAR2(500),
    RECEIVED_DATE VARCHAR2(100),
    RAW_BODY CLOB,
    STATUS VARCHAR2(50) DEFAULT 'RECEIVED' NOT NULL,
    PRIMARY_CATEGORY VARCHAR2(100),
    CONFIDENCE NUMBER(5, 4),
    IS_MULTI_LABEL NUMBER(1) DEFAULT 0,
    LABELS_JSON CLOB,
    EXECUTIVE_SUMMARY CLOB,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- Index for status queries
CREATE INDEX IDX_INTAKE_MSG_STATUS ON INTAKE_MESSAGES(STATUS);
CREATE INDEX IDX_INTAKE_MSG_CAT ON INTAKE_MESSAGES(PRIMARY_CATEGORY);

-- 3. Child Table: ATTACHMENTS
CREATE TABLE ATTACHMENTS (
    ID NUMBER(19) DEFAULT SEQ_ATTACHMENTS.NEXTVAL PRIMARY KEY,
    MESSAGE_ID NUMBER(19) NOT NULL,
    FILENAME VARCHAR2(255) NOT NULL,
    CONTENT_TYPE VARCHAR2(100),
    SIZE_BYTES NUMBER(19),
    FLAVOR VARCHAR2(50),
    LANGUAGE VARCHAR2(50) DEFAULT 'English',
    CONTENT_BYTES BLOB,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ATT_MESSAGE FOREIGN KEY (MESSAGE_ID) REFERENCES INTAKE_MESSAGES(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_ATT_MSG_ID ON ATTACHMENTS(MESSAGE_ID);

-- 4. Fact Table: ICSR_REPORTS (Safety Reports)
CREATE TABLE ICSR_REPORTS (
    ID NUMBER(19) DEFAULT SEQ_ICSR_REPORTS.NEXTVAL PRIMARY KEY,
    MESSAGE_ID NUMBER(19) NOT NULL UNIQUE,
    CASE_IDENTIFIER VARCHAR2(100),
    PATIENT_AGE VARCHAR2(50) DEFAULT 'Not stated',
    PATIENT_SEX VARCHAR2(50) DEFAULT 'Not stated',
    PATIENT_WEIGHT VARCHAR2(50) DEFAULT 'Not stated',
    PATIENT_HISTORY CLOB,
    REPORTER_NAME VARCHAR2(255) DEFAULT 'Not stated',
    REPORTER_ROLE VARCHAR2(100) DEFAULT 'Not stated',
    REPORTER_INSTITUTION VARCHAR2(255) DEFAULT 'Not stated',
    REPORTER_COUNTRY VARCHAR2(100) DEFAULT 'Not stated',
    REPORTER_CONTACT VARCHAR2(255) DEFAULT 'Not stated',
    PRODUCT_NAME VARCHAR2(255) DEFAULT 'Not stated',
    PRODUCT_DOSE VARCHAR2(100) DEFAULT 'Not stated',
    PRODUCT_FREQUENCY VARCHAR2(100) DEFAULT 'Not stated',
    PRODUCT_ROUTE VARCHAR2(100) DEFAULT 'Not stated',
    PRODUCT_LOT VARCHAR2(100) DEFAULT 'Not stated',
    PRODUCT_EXPIRY VARCHAR2(100) DEFAULT 'Not stated',
    PRODUCT_INDICATION VARCHAR2(255) DEFAULT 'Not stated',
    ADVERSE_EVENT VARCHAR2(255) DEFAULT 'Not stated',
    EVENT_ONSET VARCHAR2(100) DEFAULT 'Not stated',
    EVENT_OUTCOME VARCHAR2(100) DEFAULT 'Not stated',
    SERIOUSNESS_CRITERIA VARCHAR2(255),
    DECHALLENGE VARCHAR2(50) DEFAULT 'Not stated',
    RECHALLENGE VARCHAR2(50) DEFAULT 'Not stated',
    LAB_TESTS_JSON CLOB,
    CLINICAL_NARRATIVE CLOB,
    SOURCE_CITATIONS_JSON CLOB,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ICSR_MESSAGE FOREIGN KEY (MESSAGE_ID) REFERENCES INTAKE_MESSAGES(ID) ON DELETE CASCADE
);

-- 5. Fact Table: PQC_REPORTS (Quality Complaints)
CREATE TABLE PQC_REPORTS (
    ID NUMBER(19) DEFAULT SEQ_PQC_REPORTS.NEXTVAL PRIMARY KEY,
    MESSAGE_ID NUMBER(19) NOT NULL UNIQUE,
    PRODUCT_NAME VARCHAR2(255) DEFAULT 'Not stated',
    LOT_NUMBER VARCHAR2(100) DEFAULT 'Not stated',
    DEFECT_TYPE VARCHAR2(100) DEFAULT 'Not stated',
    DEFECT_DESCRIPTION CLOB,
    PACKAGING_BREACHED NUMBER(1) DEFAULT 0,
    PHOTO_DETECTED NUMBER(1) DEFAULT 0,
    PHOTO_DESCRIPTION CLOB,
    REQUIRES_HUMAN_REVIEW NUMBER(1) DEFAULT 0,
    SOURCE_CITATIONS_JSON CLOB,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_PQC_MESSAGE FOREIGN KEY (MESSAGE_ID) REFERENCES INTAKE_MESSAGES(ID) ON DELETE CASCADE
);

-- 6. Fact Table: MEDICAL_INFO_REPORTS (Info Requests)
CREATE TABLE MEDICAL_INFO_REPORTS (
    ID NUMBER(19) DEFAULT SEQ_MEDICAL_INFO.NEXTVAL PRIMARY KEY,
    MESSAGE_ID NUMBER(19) NOT NULL UNIQUE,
    PRODUCT_OR_TOPIC VARCHAR2(255) DEFAULT 'Not stated',
    INQUIRY_TYPE VARCHAR2(100) DEFAULT 'Not stated',
    QUESTION_TEXT CLOB,
    SOURCE_CITATIONS_JSON CLOB,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_MI_MESSAGE FOREIGN KEY (MESSAGE_ID) REFERENCES INTAKE_MESSAGES(ID) ON DELETE CASCADE
);

-- 7. Audit Trail: AUDIT_LOG (21 CFR Part 11 Compliant)
CREATE TABLE AUDIT_LOG (
    ID NUMBER(19) DEFAULT SEQ_AUDIT_LOG.NEXTVAL PRIMARY KEY,
    MESSAGE_ID NUMBER(19),
    TIMESTAMP TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    REVIEWER_USERNAME VARCHAR2(100) NOT NULL,
    ACTION VARCHAR2(50) NOT NULL,
    TARGET_FIELD VARCHAR2(100),
    ORIGINAL_VALUE CLOB,
    NEW_VALUE CLOB,
    REVIEWER_COMMENTS CLOB,
    IS_IMMUTABLE NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE INDEX IDX_AUDIT_MSG_ID ON AUDIT_LOG(MESSAGE_ID);
CREATE INDEX IDX_AUDIT_TIMESTAMP ON AUDIT_LOG(TIMESTAMP);

-- 8. Table: LITERATURE_ARTICLES (+30% Bonus Screening)
CREATE TABLE LITERATURE_ARTICLES (
    ID NUMBER(19) DEFAULT SEQ_LITERATURE_ARTICLES.NEXTVAL PRIMARY KEY,
    FILENAME VARCHAR2(255) NOT NULL,
    ARTICLE_TITLE VARCHAR2(500),
    AUTHORS VARCHAR2(500),
    JOURNAL VARCHAR2(255),
    PUBLICATION_YEAR VARCHAR2(50),
    IS_REPORTABLE NUMBER(1) DEFAULT 0,
    EXCLUSION_REASON VARCHAR2(500),
    STUDY_TYPE VARCHAR2(100),
    PATIENT_CASES_COUNT NUMBER(5) DEFAULT 0,
    SCREENING_SUMMARY CLOB,
    CASES_JSON CLOB,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 9. IMMUTABILITY TRIGGER: Prevents UPDATE or DELETE on AUDIT_LOG
CREATE OR REPLACE TRIGGER TRG_AUDIT_LOG_IMMUTABLE
BEFORE UPDATE OR DELETE ON AUDIT_LOG
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20001, '21 CFR Part 11 Compliance Violation: AUDIT_LOG records are strictly immutable. UPDATE and DELETE operations are prohibited.');
END;
/
